spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nextacademy_users
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgres

  kafka:
    bootstrap-servers: localhost:9092

jwt:
  secret: akljfabjnjlnfonafjdnfljsnsvskvlfd
  expiration-ms: 86400000 # 24 hours

info:
  app:
    name: "user-service"
    description: "User Service for NextAcademy Project"
    version: "1.0.0"

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:   #to enable shutdown endpoint in actuator to let the application gracefully shutdown and deregister from eureka
      access: "unrestricted"
  info:
    env:
      enabled: true