spring:
  application:
    name: user-service

  kafka:
    bootstrap-servers: localhost:9092

jwt:
  secret: akljfabjnjlnfonafjdnfljsnsvskvlfd
  expiration-ms: 86400000 # 24 hours

info:
  app:
    name: "user-service"
    description: "User Service for NextAcademy Project"
    version: "1.0.0"

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:   #to enable shutdown endpoint in actuator to let the application gracefully shutdown and deregister from eureka
      access: "unrestricted"
  info:
    env:
      enabled: true
